### ISSUE TITLE
[BUG] Dose it work in 1.20.4?

### ISSUE THREAD

**Issue by Logan8642** [xCykrix/DynamicLights#12] opened 2024-01-18 16:03 UTC
**Describe the Bug**:It dose not work in 1.20.4.

I've restarted the server. I've done everything.

**Comment by xCykrix** [comment] 2024-01-22 15:32
Hello @Logan8642. I am working to verify if this will require additional changes for 1.20.4. Do you encounter any errors or alerts in your console for this version?

**Comment by xCykrix** [comment] 2024-01-22 16:30
@Logan8642 1.20.4 works as expected. Please upload your console log and share it with me for further assistance here.

![2024-01-22_10 53 55](https://github.com/xCykrix/DynamicLights/assets/12182390/30125af7-dff4-4b6e-9b04-e5f4896d2a85)

1. Ensure ProtocolLib is installed with the Latest Developer Version. (https://ci.dmulloy2.net/job/ProtocolLib/)
2. Ensure you have the latest version of DynamicLights (v1.0.5 as of now)

**Comment by Logan8642** [comment] 2024-01-24 15:30
Hi, so I have tried to re install them. Change the version. But nothing works!
<img width="488" alt="Screenshot 2024-01-24 082949" src="https://github.com/xCykrix/DynamicLights/assets/157042889/2bf0552c-9f4f-4f8c-ba17-9e6aa9a39309">

**Comment by xCykrix** [comment] 2024-01-24 15:58
@Logan8642 ProtocolLib being in red means it failed to start. DynamicLights requires ProtocolLib to start and be green in `/plugins`. I used this version of ProtocolLib specifically in my Test Server.

https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar

If you have issues past that, I would need a copy of your Console Log. You can upload your latest.log or such via https://mcpaste.io/ or your preferred text sharing service. MCPaste will remove IP Addresses for your privacy.

**Comment by Logan8642** [comment] 2024-01-25 03:22
Hi! SO it wont let me download that link! but her is my console https://mcpaste.io/991b907c8d98dd4b

**Comment by Logan8642** [comment] 2024-01-25 03:22
wrong button. did not mean to close it!

**Comment by xCykrix** [comment] 2024-01-25 16:58
@Logan8642 Thanks for that console info! ProtocolLib is indeed crashing on boot.

```
25.01 03:19:55 [Server] INFO [ProtocolLib] Loading server plugin ProtocolLib v5.1.0 <-- Wrong Version
25.01 03:19:56 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
25.01 03:19:56 [Server] INFO If this problem hasn't already been reported, please open a ticket
25.01 03:19:56 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
25.01 03:19:56 [Server] INFO Stack Trace:
25.01 03:19:56 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
```

This indicates you are using an old version of ProtocolLib (5.1.0) and not the 1.20+ Version (5.2.0-SNAPSHOT). ProtocolLib's Download on Spigot does NOT support 1.20+ and must be downloaded from their Development CI: https://ci.dmulloy2.net/job/ProtocolLib/679/

![image](https://github.com/xCykrix/DynamicLights/assets/12182390/3a6a22a5-d92a-4e78-86b6-9304b4e8a5cb)

Verified as functional with Paper Build #399
ProtocolLib version 5.2.0-SNAPSHOT-679 (Jenkins Release)

```
> plugins
[11:55:54 INFO]: Server Plugins (2):
[11:55:54 INFO]: Bukkit Plugins:
[11:55:54 INFO]:  - DynamicLights, ProtocolLib
> version ProtocolLib
[11:55:57 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[11:55:57 INFO]: Provides read/write access to the Minecraft protocol.
[11:55:57 INFO]: Authors: dmulloy2 and comphenix
> version DynamicLights
[11:56:01 INFO]: DynamicLights version 1.0.5-SNAPSHOT
[11:56:01 INFO]: Emit Light from Held Items using the 1.17 Light Blocks.
[11:56:01 INFO]: Website: https://www.spigotmc.org/resources/dynamiclights.110707/
[11:56:01 INFO]: Author: xCykrix
```

Once ProtocolLib is updated, DynamicLights should work for you.

**Comment by Logan8642** [comment] 2024-01-27 05:27
Hi! So Im not able to download it! 
<img width="263" alt="image" src="https://github.com/xCykrix/DynamicLights/assets/157042889/12aa3282-45c3-4216-bced-bfff19bb3fc8">

**Comment by Logan8642** [comment] 2024-01-27 05:28
I take that back

**Comment by xCykrix** [comment] 2024-02-03 00:20
Closing as I am not able to reproduce this issue.

Once updated, you should be able to proceed. If you are having issues in downloading ProtocolLib, I would recommend reaching out to ProtocolLib Support Channels as that is a third party to DynamicLights.

**Closed by xCykrix** 2024-02-03 00:20 UTC
Labels: State: Blocked, Type: Bug, Type: Dependencies, Meta: Question
